apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosoair
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contosoair
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: contosoair
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: angular-web-app
        image: eliyareg2.azurecr.io/contosoair-jenkins/contosoair:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      
---
apiVersion: v1
kind: Service
metadata:
  name: contosoair
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: contosoair